name: 'Test and lint'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2.0-preview1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install dependencies
        run: bundle install
      - name: Lint Ruby files
        run: bundle exec rubocop
      - name: Run RSpec tests
        run: bundle exec rspec